### PR TITLE
Fixed `local variable 'ynab_account_id' referenced before assignment`

### PR DESCRIPTION
**Pull request by marc-bnt**
This fixes an error when using the `BUNQ_ACCOUNT_ID` and `YNAB_ACCOUNT_ID` variables.

NOTE: The new default behavior with all accounts seems nice, however, it also includes archived bunq accounts. I have about 40 archived accounts, and for every account it does a separate YNAB API request.

Since the YNAB API is rate limited at 200 requests/hour, this quickly results in a `Too many requests` error.

### CODE REVIEW

**Review by rvdh — APPROVED** [review]
Thanks for your contribution! :)

As for your note regarding the rate limiting: please open a seperate issue for this. I'll look into the possibility of excluding archived accounts from syncing.

**Comment by rvdh** [comment]
Also, please remove the bunq2ynab.zip file from this PR, I'll regenerate it from the master branch.

**Comment by marc-bnt** [comment]
Done

**Comment by rvdh** [comment]
Thanks again! 👍

**Pull request merged**
